### ISSUE TITLE
Module initialization error when deployed to AWS

### ISSUE THREAD

**Issue by clsedlacek** [escaladesports/goalrilla-reviews-api#1]
START RequestId: 14c4ceba-ff9d-11e7-8343-616248558927 Version: $LATEST
    module initialization error: TypeError
        at requireFromString (/var/task/_optimize/goalrilla-reviews-api-staging-
    postReviewV1/src/handler.js:243573:8)
        at exports.default (/var/task/_optimize/goalrilla-reviews-api-staging-
    postReviewV1/src/handler.js:20412:41)
        at exports.default (/var/task/_optimize/goalrilla-reviews-api-staging-
    postReviewV1/src/handler.js:20334:34)
        at Object.656../api.js (/var/task/_optimize/goalrilla-reviews-api-staging-
    postReviewV1/src/handler.js:256356:493)
        at s (/var/task/_optimize/goalrilla-reviews-api-staging-postReviewV1/src/handler.js:1:683)
        at e (/var/task/_optimize/goalrilla-reviews-api-staging-postReviewV1/src/handler.js:1:854)
        at /var/task/_optimize/goalrilla-reviews-api-staging-postReviewV1/src/handler.js:1:872
        at a (/var/task/_optimize/goalrilla-reviews-api-staging-postReviewV1/src/handler.js:1:150)
        at Object.<anonymous> (/var/task/_optimize/goalrilla-reviews-api-staging-
    postReviewV1/src/handler.js:1:385)
        at Module._compile (module.js:570:32)
    END RequestId: 14c4ceba-ff9d-11e7-8343-616248558927
    REPORT RequestId: 14c4ceba-ff9d-11e7-8343-616248558927	Duration: 4.74 ms	Billed 
    Duration: 100 ms 	Memory Size: 1024 MB	Max Memory Used: 194 MB

**Comment by kennedyrose** [comment]
Still looking into this. For now, just put any secure env variables in Travis and deploy by pushing to GH. Any variables that don't need to be secured can just go into the repo for now.

**Comment by kennedyrose** [comment]
Make sure to comment out env import code in the handler.

**Comment by kennedyrose** [comment]
Scratch that. Update envdotjs to 1.4.4.
